#!/usr/bin/php
<?php


$PARAMS = array_slice($argv, 1);

if($PARAMS)
{
    $TXT = implode(PHP_EOL, array_map('trim', $PARAMS));

    if(empty($TXT)) exit;

    $POST = [
        'body' => $TXT,
        'from' => 'data2',
    ];

    $RET = data2_notify('https://whatsapp-notify.data2.com.br/data2/server/', $POST);
    $RET = json_decode($RET, true);

    if($RET['status'])
    {
        exit('sucesso!');
    }
    else
    {
        echo '! ERROR !';
    }
}

#print_r($PARAMS);

function data2_notify($url, $POST = false, $FLG_FOLLOW_REDIRECT = false)
{
	$ch = curl_init();
	$timeout = 10;
	$header = array();

	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $header);

	curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36');

	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

	if($FLG_FOLLOW_REDIRECT)
	{
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	}
  
    if($POST && is_array($POST))
    {
        curl_setopt($ch,CURLOPT_POST, true);
        curl_setopt($ch,CURLOPT_POSTFIELDS, http_build_query($POST));
    }

    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

	#curl_setopt($ch, CURLOPT_COOKIEJAR, APP_PATH . 'cookie.cookie');
    #curl_setopt($ch, CURLOPT_COOKIEFILE, APP_PATH . 'cookie.cookie');

	$data = curl_exec($ch);
	curl_close($ch);

	return $data;
}

